export const KEY_UPDATE = 'KEY_UPDATE';
export const APP_INSTRUCTIONS_SET = 'APP_INSTRUCTIONS_SET';
export const SOCKET_SET_USERS_IDS = 'SOCKET_SET_USERS_IDS';
export const SOCKET_SET_USER = 'SOCKET_SET_USER';
export const SOCKET_REMOVE_USERS_IDS = 'SOCKET_REMOVE_USERS_IDS';
export const SOCKET_REQ_PARTNER = 'SOCKET_REQ_PARTNER';
export const SOCKET_REQ_PARTNER_CONFIRM = 'SOCKET_REQ_PARTNER_CONFIRM';
export const SOCKET_MSG_RECEIVE = 'SOCKET_MSG_RECEIVE';
export const SOCKET_MSG_SEND = 'SOCKET_MSG_SEND';
export const SOCKET_MSG_SEND_NO_REPLY = 'SOCKET_MSG_SEND_NO_REPLY';
export const SOCKET_MSG_DELETE = 'SOCKET_MSG_DELETE';

